"""Auto-bootstrap of agent containers — magic onboarding.

Ensures `ai-company-agent-<name>-1` is running, creating it from
`docker-compose.override.yml` when needed. Three cases:

  1. Container already running -> noop
  2. Container exists but stopped/exited -> start + readiness check
  3. Container doesn't exist -> reconcile (generates override.yml if missing) +
     parse override + create via docker SDK + readiness check

MVP: applies only to agent-executor (predictable service def, generated by
reconcile itself with a fixed schema). Don't generalize prematurely to
any agent — the service-def->SDK kwargs mapping is fragile.
"""
from __future__ import annotations

import asyncio
from pathlib import Path

import docker
import structlog
import yaml


log = structlog.get_logger("agent_bootstrap")

OVERRIDE_PATH = Path("/workspace/docker-compose.override.yml")


def _compose_project() -> str:
    """Compose stack project name. Default `ai-company` (framework
    default), overridden by the instance .env (`COMPOSE_PROJECT_NAME=...`)."""
    import os
    env = _load_dot_env()
    return (
        os.environ.get("COMPOSE_PROJECT_NAME")
        or env.get("COMPOSE_PROJECT_NAME")
        or "ai-company"
    )


def _container_name(agent: str) -> str:
    return f"{_compose_project()}-agent-{agent}-1"


def _service_name(agent: str) -> str:
    return f"agent-{agent}"


async def _wait_running(container, timeout: float) -> None:
    """Polling: waits for status=running + claude CLI available to user node."""
    deadline = asyncio.get_event_loop().time() + timeout
    interval = 0.5
    while asyncio.get_event_loop().time() < deadline:
        await asyncio.to_thread(container.reload)
        if container.status == "running":
            try:
                rc, _ = await asyncio.to_thread(
                    container.exec_run,
                    ["which", "claude"],
                    user="node",
                )
                if rc == 0:
                    return
            except Exception:
                pass
        await asyncio.sleep(interval)
        interval = min(interval * 1.5, 3.0)
    raise TimeoutError(
        f"container {container.name} did not become ready within {timeout}s "
        f"(last status={container.status})"
    )


def _service_to_run_kwargs(service: dict, container_name: str, service_name: str) -> dict:
    """Converts a compose service def to docker SDK containers.run kwargs.

    Covers the subset reconcile generates for agent-executor: image, environment,
    volumes (bind mounts), labels, restart, working_dir, command, networks.
    """
    kwargs: dict = {
        "image": service["image"],
        "name": container_name,
        "detach": True,
        "labels": {
            "com.docker.compose.project": _compose_project(),
            "com.docker.compose.service": service_name,
            "com.docker.compose.oneoff": "False",
            **(service.get("labels") or {}),
        },
    }

    # Environment: dict or list. Compose supports both.
    env = service.get("environment")
    if isinstance(env, list):
        kwargs["environment"] = env
    elif isinstance(env, dict):
        kwargs["environment"] = {str(k): str(v) for k, v in env.items()}

    # Volumes: list of "host:container[:mode]" strings -> SDK wants a dict.
    # IMPORTANT: expand ${VAR:-default} BEFORE splitting — the `:-` in the
    # default contains a `:` that confuses a naive split. The Compose CLI resolves
    # ${...} on the host before create; without the CLI, web substitutes manually.
    vols: dict = {}
    for v in service.get("volumes") or []:
        if not isinstance(v, str):
            continue
        expanded = _expand_env_vars(v)
        parts = expanded.split(":")
        if len(parts) == 2:
            host, container = parts
            mode = "rw"
        elif len(parts) == 3:
            host, container, mode = parts
        else:
            continue
        vols[host] = {"bind": container, "mode": mode}
    if vols:
        kwargs["volumes"] = vols

    if service.get("working_dir"):
        kwargs["working_dir"] = service["working_dir"]
    if service.get("command"):
        cmd = service["command"]
        kwargs["command"] = cmd if isinstance(cmd, list) else cmd
    if service.get("user"):
        kwargs["user"] = str(service["user"])

    restart = service.get("restart")
    if restart:
        kwargs["restart_policy"] = {"Name": restart}

    # Network: agents use the compose project's default network
    # (<project>_default).
    kwargs["network"] = f"{_compose_project()}_default"

    return kwargs


_ENV_CACHE: dict[str, str] | None = None


def _load_dot_env() -> dict[str, str]:
    global _ENV_CACHE
    if _ENV_CACHE is not None:
        return _ENV_CACHE
    env: dict[str, str] = {}
    p = Path("/workspace/.env")
    if p.exists():
        for line in p.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            env[k.strip()] = v.strip()
    _ENV_CACHE = env
    return env


def _expand_env_vars(s: str) -> str:
    """Expands ${VAR} and ${VAR:-default} using /workspace/.env. Relative
    paths (./instance/foo, ../agents) are relative to manager/ — the
    docker daemon resolves them relative to the compose-project-dir, but here
    (direct SDK) they must be absolute. PROJECT_ROOT_HOST points to manager/."""
    import os
    import re

    project_root_host = os.environ.get("PROJECT_ROOT_HOST", "")
    env = _load_dot_env()
    # Host user's HOME (passed via compose env HOST_HOME=${HOME}).
    # The Compose CLI normally resolves ${HOME} on the host before creating
    # containers; without the CLI, web substitutes manually here.
    host_home = os.environ.get("HOST_HOME") or os.environ.get("HOME") or ""

    def repl(m: "re.Match") -> str:
        var = m.group(1)
        default = m.group(2) or ""
        if var == "HOME":
            return host_home or default
        return env.get(var) or default

    # Accepts ${VAR}, ${VAR:-default}, ${VAR-default}. The default may contain
    # `:` (e.g. paths) — uses `[^}]*`, which stops at the closing `}`.
    expanded = re.sub(r"\$\{([A-Z_][A-Z0-9_]*)(?::?-([^}]*))?\}", repl, s)

    # Normalize relative -> absolute paths (relative to manager/)
    if expanded.startswith(("./", "../")) and project_root_host:
        from pathlib import Path as _P
        expanded = str((_P(project_root_host) / expanded).resolve())
    return expanded


async def ensure_agent_running(agent: str, timeout: float = 45.0) -> None:
    """Ensures ai-company-agent-<name>-1 is running. Idempotent.

    Callers use it before docker exec'ing into the container (e.g. hire generation,
    onboard propose-agents). Raises RuntimeError/TimeoutError on failure.
    """
    name = _container_name(agent)
    service = _service_name(agent)
    client = await asyncio.to_thread(docker.from_env)

    # Case 1: already exists + running
    try:
        container = await asyncio.to_thread(client.containers.get, name)
        await asyncio.to_thread(container.reload)
        if container.status == "running":
            log.debug("ensure.already_running", agent=agent)
            return
        # Case 2: exists but stopped
        log.info("ensure.starting", agent=agent, prev_status=container.status)
        await asyncio.to_thread(container.start)
        await _wait_running(container, timeout)
        return
    except docker.errors.NotFound:
        pass  # fall through to case 3

    # Case 3: doesn't exist — generate override if missing + create via SDK
    log.info("ensure.bootstrapping", agent=agent)
    if not OVERRIDE_PATH.exists():
        log.info("ensure.running_reconcile", reason="override.yml missing")
        from . import hire as _hire
        await asyncio.to_thread(_hire.run_reconcile)

    if not OVERRIDE_PATH.exists():
        raise RuntimeError(
            f"override.yml still missing after reconcile — cannot bootstrap {agent}"
        )

    override = yaml.safe_load(OVERRIDE_PATH.read_text(encoding="utf-8")) or {}
    services = (override.get("services") or {})
    svc = services.get(service)
    if not svc:
        raise RuntimeError(
            f"service '{service}' not found in override.yml — "
            f"is '{agent}' registered in agents.yaml?"
        )

    kwargs = _service_to_run_kwargs(svc, container_name=name, service_name=service)
    log.info("ensure.creating", agent=agent, image=kwargs.get("image"))

    try:
        container = await asyncio.to_thread(client.containers.run, **kwargs)
    except docker.errors.APIError as e:
        # Race: another caller may have created it between our get(NotFound) and run().
        if "Conflict" in str(e) or "already in use" in str(e):
            container = await asyncio.to_thread(client.containers.get, name)
        else:
            raise

    await _wait_running(container, timeout)
    log.info("ensure.ready", agent=agent)
